# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.56.0"

default_platform :ios

platform :ios do
  # ipa包文件路径
  ipaDirFir = File.dirname(Dir.pwd) + "/ipa_firim"
  ipaDirAppStore = File.dirname(Dir.pwd) + "/ipa_appStore"
  kFirmToken = "*"


  desc "发布到AppStore"
  lane :release do
    clear_cache_files()
    cocoapods
    updateBuildVersion(false)
    gym(
      output_directory: ipaDirAppStore,
      scheme: project_name,
      export_options: {
        method: 'app-store',

      }
    )
    deliver(force: true)

    handleDingTalkParams(ipaDirAppStore)
  end


  desc "发布到Fir"
  lane :fir do
    cocoapods
    updateBuildVersion(true)
    gym(
      clean: true,
      output_directory: ipaDirFir,
      scheme: project_name,
      configuration: 'Debug',
      include_symbols: true,
      export_options: {
        method: 'development'
      }
    )
    firim(firim_api_token: kFirmToken)

    handleDingTalkParams(ipaDirFir)
  end


  desc "测试通道"
  lane :test do |lane|
    puts "---#{project_name}--"
    puts "-11--#{lane_context[SharedValues::LANE_NAME]}--"
    # puts "user name is: #{`whoami`}"  

    # puts "---#{git_last_log_dic}--"
    # update_build({plist: plistPath()})
    handleDingTalkParams(ipaDirFir)

  end


  desc "更新buildVersion"
  def updateBuildVersion(showHash = true)
    plistPath = plist_path({projectname: project_name})
    puts "---#{plistPath}--"
    update_build({plist: plistPath, showHash: showHash})
  end


  desc "钉钉插件参数设置"
  def handleDingTalkParams(ipaDir)
    appPath = ipaDir + "/#{project_name}.ipa"
    appUrl  = "firim下载网址"
    appIcon = "appConnect图标链接"
    dingUrl = "*"#{测试群}

    gitDesc = markdown_desc({keys: [:last_git_commit_note,:last_git_commit_hash,:last_git_commit_time], isChinese: true})

    params = {
                appPath: appPath,
                appUrl: appUrl,
                appIcon: appIcon,
                dingUrl: dingUrl,
                # markdownText: gitDesc
              }
    puts "---#{params}--"
    dingdingtalk_robot(params)

    # gitDesc = gitLastDicDes(gitLastDic,true)
    # handleDingTalk(appPath: params[:appPath], appUrl: params[:appUrl], appIcon: params[:appIcon], dingUrl: params[:dingUrl], markdownText: gitDesc)
    # puts "101---#{ipaName}--"
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    # pushMsgToSlack(lane.to_json)

  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

  desc "推送通知到slack"
  def pushMsgToSlack(lane = nil, exception = nil)
    if exception != nil
      slack(
        message: exception.message,
        success: false,
        slack_url: "https://hooks.slack.com/services/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",
        payload: {
            "Build Date" => Time.new.strftime("%Y-%m-%d %H:%M:%S"),
            "Built by" => "shang1219178163",
          }
      )
    end

    platformInfo = lane.include?("fir") == true ? "已更新至fir" : "已上传至AppStoreConnect"
    slack(
      # message: "<项目名称> Successfully deployed new App Update.",
      message: platformInfo,
      slack_url: "https://hooks.slack.com/services/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",
      default_payloads: [:lane, :git_branch, :git_author, :last_git_commit],
      attachment_properties: {
        thumb_url: "app图标链接",
        author_name: "shang1219178163",
        pretext: "app副标题",
        # fields: [{
        #   title: "时间日期",
        #   value: Time.new.strftime("%Y-%m-%d %H:%M:%S"),
        #   short: true
        # },
        # {
        #   title: "AppUrl",
        #   value: "https://fir.im/zk9r",
        #   short: true
        # }]
      }
    )
  end
end
