source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Xcode11Project' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for Xcode11Project
  pod 'SnapKit'
  pod 'SnapKitExtend'
  
  pod 'SwiftExpand'

end
